import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

const STEPS = ['Basic Info', 'Error Input', 'AI Analysis', 'Review', 'Export']
const API_BASE = import.meta.env.DEV ? 'http://localhost:3001/api' : '/api'

export default function NewReport() {
  const navigate = useNavigate()
  const [currentStep, setCurrentStep] = useState(0)
  const [formData, setFormData] = useState({
    title: '',
    project: '',
    severity: 'medium',
    errorInput: ''
  })
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [analysisProgress, setAnalysisProgress] = useState(0)

  const updateFormData = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const canProceed = () => {
    switch (currentStep) {
      case 0: return formData.title && formData.project
      case 1: return formData.errorInput.length > 10
      case 2: return report !== null
      case 3: return true
      default: return false
    }
  }

  const generateReport = async () => {
    setLoading(true)
    setCurrentStep(2)

    // Simulate progress
    const progressInterval = setInterval(() => {
      setAnalysisProgress(prev => {
        if (prev >= 90) {
          clearInterval(progressInterval)
          return 90
        }
        return prev + 10
      })
    }, 300)

    try {
      const res = await fetch(`${API_BASE}/reports/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: formData.title,
          project: formData.project,
          severity: formData.severity,
          errorInput: formData.errorInput
        })
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate report')
      }

      setReport(data.report)
      setAnalysisProgress(100)
      clearInterval(progressInterval)

      setTimeout(() => setCurrentStep(3), 500)
    } catch (err) {
      alert(err.message)
      setCurrentStep(1)
    } finally {
      clearInterval(progressInterval)
      setLoading(false)
    }
  }

  const saveReport = async () => {
    try {
      const res = await fetch(`${API_BASE}/reports`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...formData,
          generated_title: report.title,
          generated_summary: report.summary,
          severity: report.severity,
          steps_to_reproduce: report.steps,
          expected_behavior: report.expected,
          actual_behavior: report.actual,
          root_cause_analysis: report.rootCause,
          suggested_fix: report.fix,
          tags: report.tags,
          ai_confidence: report.confidence,
          original_input: formData.errorInput
        })
      })

      const data = await res.json()
      if (res.ok) {
        navigate(`/report/${data.report.id}`)
      }
    } catch (err) {
      alert('Failed to save report')
    }
  }

  const exportMarkdown = () => {
    const md = `# ${report.title}

## Summary
${report.summary}

## Severity
${report.severity}

## Steps to Reproduce
${report.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Expected Behavior
${report.expected}

## Actual Behavior
${report.actual}

## Root Cause Analysis
${report.rootCause}

## Suggested Fix
\`\`\`
${report.fix}
\`\`\`

## Tags
${report.tags.join(', ')}

---
*Generated by BugGenie AI*
`
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/\s+/g, '_')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportJSON = () => {
    const json = JSON.stringify(report, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.title.replace(/\s+/g, '_')}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const copyToClipboard = () => {
    const md = `# ${report.title}\n\n## Summary\n${report.summary}\n\n## Steps\n${report.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}`
    navigator.clipboard.writeText(md)
    alert('Copied to clipboard!')
  }

  return (
    <div className="wizard">
      <div className="page-header">
        <h1 className="page-title">Generate Bug Report</h1>
        <p className="page-subtitle">Let AI transform your error descriptions into structured reports</p>
      </div>

      <div className="wizard-steps">
        {STEPS.map((step, i) => (
          <div key={step} className={`wizard-step ${i === currentStep ? 'active' : ''} ${i < currentStep ? 'completed' : ''}`}>
            <div className="step-number">{i < currentStep ? '✓' : i + 1}</div>
            <span className="step-label">{step}</span>
          </div>
        ))}
      </div>

      <div className="wizard-content">
        {currentStep === 0 && (
          <div>
            <h2 style={{ marginBottom: 24 }}>Basic Information</h2>
            <div className="form-group">
              <label className="form-label">Report Title *</label>
              <input
                type="text"
                className="form-input"
                value={formData.title}
                onChange={(e) => updateFormData('title', e.target.value)}
                placeholder="e.g., Login page crashes on Safari"
              />
            </div>
            <div className="form-group">
              <label className="form-label">Project *</label>
              <select
                className="form-select"
                value={formData.project}
                onChange={(e) => updateFormData('project', e.target.value)}
              >
                <option value="">Select project...</option>
                <option value="frontend">Frontend App</option>
                <option value="backend">Backend API</option>
                <option value="mobile">Mobile App</option>
                <option value="infrastructure">Infrastructure</option>
                <option value="other">Other</option>
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Initial Severity (AI may adjust)</label>
              <select
                className="form-select"
                value={formData.severity}
                onChange={(e) => updateFormData('severity', e.target.value)}
              >
                <option value="critical">Critical</option>
                <option value="high">High</option>
                <option value="medium">Medium</option>
                <option value="low">Low</option>
              </select>
            </div>
          </div>
        )}

        {currentStep === 1 && (
          <div>
            <h2 style={{ marginBottom: 24 }}>Error Description</h2>
            <div className="form-group">
              <label className="form-label">Paste error message, stack trace, or describe the issue *</label>
              <textarea
                className="form-textarea"
                value={formData.errorInput}
                onChange={(e) => updateFormData('errorInput', e.target.value)}
                placeholder="TypeError: Cannot read property 'map' of undefined at App.js:45

Stack trace:
  at renderWithHooks (react-dom.development.js:14810)
  at mountIndeterminateComponent (react-dom.development.js:17492)
..."
                style={{ minHeight: 300, fontFamily: 'var(--font-primary)' }}
              />
            </div>
          </div>
        )}

        {currentStep === 2 && (
          <div className="loading-container">
            <div className="loading-dots">
              <div className="loading-dot"></div>
              <div className="loading-dot"></div>
              <div className="loading-dot"></div>
            </div>
            <p className="loading-text">AI is analyzing your bug report...</p>
            <div style={{ width: 200, height: 4, background: 'var(--color-border)', borderRadius: 2, marginTop: 16 }}>
              <div style={{ width: `${analysisProgress}%`, height: '100%', background: 'var(--color-accent)', borderRadius: 2, transition: 'width 0.3s ease' }}></div>
            </div>
            <p style={{ marginTop: 12, fontSize: '0.8rem', color: 'var(--color-text-secondary)' }}>
              {analysisProgress < 30 && 'Analyzing error patterns...'}
              {analysisProgress >= 30 && analysisProgress < 60 && 'Generating root cause analysis...'}
              {analysisProgress >= 60 && analysisProgress < 90 && 'Formulating fix suggestions...'}
              {analysisProgress >= 90 && 'Finalizing report...'}
            </p>
          </div>
        )}

        {currentStep === 3 && report && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
              <h2>Review Generated Report</h2>
              <div className="confidence-score">
                <span>AI Confidence:</span>
                <div className="confidence-bar">
                  <div className="confidence-fill" style={{ width: `${report.confidence}%` }}></div>
                </div>
                <span>{report.confidence}%</span>
              </div>
            </div>

            <div className="report-sections">
              <div className="report-section">
                <div className="report-section-title">Title</div>
                <div className="report-section-content">{report.title}</div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Severity</div>
                <div className="report-section-content">
                  <span className={`badge badge-${report.severity}`}>{report.severity}</span>
                </div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Summary</div>
                <div className="report-section-content">{report.summary}</div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Steps to Reproduce</div>
                <div className="report-section-content">
                  {report.steps.map((step, i) => (
                    <div key={i}>{i + 1}. {step}</div>
                  ))}
                </div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Expected Behavior</div>
                <div className="report-section-content">{report.expected}</div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Actual Behavior</div>
                <div className="report-section-content">{report.actual}</div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Root Cause Analysis</div>
                <div className="report-section-content">{report.rootCause}</div>
              </div>

              <div className="report-section">
                <div className="report-section-title">Suggested Fix</div>
                <pre className="report-section-content" style={{ whiteSpace: 'pre-wrap', fontFamily: 'var(--font-primary)', fontSize: '0.85rem', background: 'rgba(0,0,0,0.2)', padding: 12, borderRadius: 6 }}>{report.fix}</pre>
              </div>

              <div className="report-section">
                <div className="report-section-title">Tags</div>
                <div className="report-section-content">{report.tags.join(', ')}</div>
              </div>
            </div>
          </div>
        )}

        {currentStep === 4 && report && (
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '4rem', marginBottom: 16 }}>✅</div>
            <h2 style={{ marginBottom: 8 }}>Report Ready!</h2>
            <p style={{ color: 'var(--color-text-secondary)', marginBottom: 32 }}>
              Your bug report has been generated. Choose how to proceed.
            </p>

            <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
              <button className="btn btn-primary btn-large" onClick={saveReport}>
                Save to Database
              </button>
              <button className="btn btn-secondary btn-large" onClick={exportMarkdown}>
                Export Markdown
              </button>
              <button className="btn btn-secondary btn-large" onClick={exportJSON}>
                Export JSON
              </button>
              <button className="btn btn-secondary btn-large" onClick={copyToClipboard}>
                Copy to Clipboard
              </button>
            </div>
          </div>
        )}

        <div className="wizard-actions">
          {currentStep > 0 && currentStep < 4 && (
            <button className="btn btn-secondary" onClick={() => setCurrentStep(currentStep - 1)}>
              ← Back
            </button>
          )}
          {currentStep < 2 && (
            <button
              className="btn btn-primary"
              style={{ marginLeft: 'auto' }}
              disabled={!canProceed()}
              onClick={() => setCurrentStep(currentStep + 1)}
            >
              Continue →
            </button>
          )}
          {currentStep === 2 && (
            <button
              className="btn btn-primary"
              style={{ marginLeft: 'auto' }}
              disabled={loading}
              onClick={generateReport}
            >
              {loading ? 'Generating...' : 'Generate Report'}
            </button>
          )}
          {currentStep === 3 && (
            <button
              className="btn btn-primary"
              style={{ marginLeft: 'auto' }}
              onClick={() => setCurrentStep(4)}
            >
              Continue to Export →
            </button>
          )}
        </div>
      </div>
    </div>
  )
}