import { useState, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'

const API_BASE = import.meta.env.DEV ? 'http://localhost:3001/api' : '/api'

export default function ReportDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [deleteModal, setDeleteModal] = useState(false)

  useEffect(() => {
    fetchReport()
  }, [id])

  const fetchReport = async () => {
    try {
      const res = await fetch(`${API_BASE}/reports/${id}`)
      const data = await res.json()
      setReport(data.report)
    } catch (err) {
      console.error('Failed to fetch report:', err)
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async () => {
    try {
      const res = await fetch(`${API_BASE}/reports/${id}`, { method: 'DELETE' })
      if (res.ok) {
        navigate('/history')
      }
    } catch (err) {
      alert('Failed to delete report')
    }
  }

  const exportMarkdown = () => {
    if (!report) return
    const md = `# ${report.generated_title}

## Summary
${report.generated_summary}

## Severity
${report.severity}

## Steps to Reproduce
${report.steps_to_reproduce}

## Expected Behavior
${report.expected_behavior}

## Actual Behavior
${report.actual_behavior}

## Root Cause Analysis
${report.root_cause_analysis}

## Suggested Fix
\`\`\`
${report.suggested_fix}
\`\`\`

## Tags
${report.tags || ''}

---
*Generated by BugGenie AI*
`
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.generated_title?.replace(/\s+/g, '_')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportJSON = () => {
    if (!report) return
    const json = JSON.stringify(report, null, 2)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${report.generated_title?.replace(/\s+/g, '_')}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const copyToClipboard = () => {
    if (!report) return
    const text = `${report.generated_title}\n\n${report.generated_summary}\n\n${report.steps_to_reproduce}`
    navigator.clipboard.writeText(text)
    alert('Copied to clipboard!')
  }

  const getSeverityClass = (severity) => {
    const map = { critical: 'badge-critical', high: 'badge-high', medium: 'badge-medium', low: 'badge-low' }
    return map[severity?.toLowerCase()] || 'badge-medium'
  }

  if (loading) {
    return (
      <div>
        <div className="skeleton" style={{ height: 40, marginBottom: 24, width: 300 }}></div>
        <div className="skeleton" style={{ height: 400 }}></div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="empty-state">
        <div className="empty-state-icon">❌</div>
        <h3 className="empty-state-title">Report not found</h3>
        <p className="empty-state-text">The requested report doesn't exist</p>
        <Link to="/history" className="btn btn-primary">
          Back to History
        </Link>
      </div>
    )
  }

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
        <div>
          <Link to="/history" style={{ fontSize: '0.9rem', color: 'var(--color-text-secondary)' }}>
            ← Back to History
          </Link>
          <h1 style={{ marginTop: 8 }}>{report.generated_title}</h1>
          <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.9rem' }}>
            Created {new Date(report.created_at).toLocaleDateString('en-US', {
              year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
            })}
            {report.project && ` • ${report.project}`}
          </p>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-secondary btn-icon" onClick={exportMarkdown} title="Export Markdown">
            ↓
          </button>
          <button className="btn btn-secondary btn-icon" onClick={exportJSON} title="Export JSON">
            ⊞
          </button>
          <button className="btn btn-secondary btn-icon" onClick={copyToClipboard} title="Copy">
            ⎘
          </button>
          <button className="btn btn-danger btn-icon" onClick={() => setDeleteModal(true)} title="Delete">
            🗑
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 24 }}>
        <span className={`badge badge-${report.severity?.toLowerCase()}`} style={{ fontSize: '0.9rem', padding: '8px 16px' }}>
          {report.severity || 'Medium'}
        </span>
        {report.ai_confidence && (
          <div className="confidence-score">
            <span>AI Confidence:</span>
            <div className="confidence-bar" style={{ width: 80, height: 8 }}>
              <div className="confidence-fill" style={{ width: `${report.ai_confidence}%` }}></div>
            </div>
            <span>{report.ai_confidence}%</span>
          </div>
        )}
      </div>

      <div className="report-sections">
        <div className="report-section">
          <div className="report-section-title">Summary</div>
          <div className="report-section-content">{report.generated_summary}</div>
        </div>

        <div className="report-section">
          <div className="report-section-title">Steps to Reproduce</div>
          <div className="report-section-content" style={{ whiteSpace: 'pre-wrap' }}>
            {report.steps_to_reproduce}
          </div>
        </div>

        <div className="report-section">
          <div className="report-section-title">Expected Behavior</div>
          <div className="report-section-content">{report.expected_behavior}</div>
        </div>

        <div className="report-section">
          <div className="report-section-title">Actual Behavior</div>
          <div className="report-section-content">{report.actual_behavior}</div>
        </div>

        <div className="report-section">
          <div className="report-section-title">Root Cause Analysis</div>
          <div className="report-section-content">{report.root_cause_analysis}</div>
        </div>

        <div className="report-section">
          <div className="report-section-title">Suggested Fix</div>
          <pre style={{
            whiteSpace: 'pre-wrap',
            fontFamily: 'var(--font-primary)',
            fontSize: '0.85rem',
            background: 'rgba(0,0,0,0.2)',
            padding: 16,
            borderRadius: 6,
            overflow: 'auto'
          }}>{report.suggested_fix}</pre>
        </div>

        {report.tags && (
          <div className="report-section">
            <div className="report-section-title">Tags</div>
            <div className="report-section-content">{report.tags}</div>
          </div>
        )}

        {report.original_input && (
          <div className="report-section">
            <div className="report-section-title">Original Input</div>
            <pre style={{
              whiteSpace: 'pre-wrap',
              fontFamily: 'var(--font-primary)',
              fontSize: '0.8rem',
              background: 'rgba(0,0,0,0.2)',
              padding: 16,
              borderRadius: 6,
              color: 'var(--color-text-secondary)',
              maxHeight: 200,
              overflow: 'auto'
            }}>{report.original_input}</pre>
          </div>
        )}
      </div>

      {deleteModal && (
        <div className="modal-overlay" onClick={() => setDeleteModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3 className="modal-title">Delete Report?</h3>
              <button className="modal-close" onClick={() => setDeleteModal(false)}>×</button>
            </div>
            <p style={{ color: 'var(--color-text-secondary)' }}>
              This action cannot be undone. The report will be permanently deleted.
            </p>
            <div className="modal-actions">
              <button className="btn btn-secondary" onClick={() => setDeleteModal(false)}>
                Cancel
              </button>
              <button className="btn btn-danger" onClick={handleDelete}>
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}